### ISSUE TITLE
Is there any provision to work behind Proxy environment with authorization ?

### ISSUE THREAD

**Issue by PatelParas** [hannseman/hipsaint#17]
i am running nagios behind proxy firewall, 
how can i pass pass proxy setting for hipsaint to connect public url ?

**Comment by mvisonneau** [comment]
I am also interested on this feature. Are you still planning on implementing it ?

**Comment by PatelParas** [comment]
@mvisonneau I have hard-coded to quick fix. in my personal fork. 
https://github.com/PatelParas/hipsaint/commit/c009a9c2bcab59c77bc52e85560ef2090ca841c0
check this if you are interested.

**Comment by hannseman** [comment]
Just pushed a commit which adds the `--proxy` argument for specifying an http proxy. Will push to pypi ASAP. Thanks for your work @PatelParas
