### ISSUE TITLE
duplicate notifications

### ISSUE THREAD

**Issue by scottsuch** [hannseman/hipsaint#30]
Every notification generated by my icinga2 setup is generating duplicate messages in hipchat. Have you seen this before?
![screenshot 2015-09-25 09 48 06](https://cloud.githubusercontent.com/assets/897179/10102104/b3447862-636a-11e5-931e-82ebf385be09.png)
Let me know what would be useful in debugging this isseue.

Also, thank you so much for putting this project out there, it's a very convenient thing to have =)

**Comment by hannseman** [comment]
Sorry I have not encountered this before. Are you sure that you haven't created duplicate contacts or something like that?

**Comment by scottsuch** [comment]
Sorry for the false alarm. I think I've found what's happening. The configuration provided in your documentation suggests just sending to the `user_groups = [ "icingaadmins" ]` so for each user in that group it sends a message which isn't a problem unless you have multiple users in the icingaadmins group =).

**Comment by hannseman** [comment]
Ah! Good to hear you solved it. :)
