### ISSUE TITLE
bug hipsaint/messages.py - 

### ISSUE THREAD

**Issue by taherbs** [hannseman/hipsaint#31]
I have noticed that their is bug on messages.py/Line 40: 
self.urlv2 = 'https://{0}/v2/room/{1}/notification'.format(self.host, self.room_id)
This should be:
self.urlv2 = 'https://{0}/v2/room/{1}/message'.format(self.host, self.room_id)
So you have to change "notification" by "message" for the message to pass via hipchat API V2.

**Comment by hannseman** [comment]
What bug are you encountering?
