### ISSUE TITLE
Need more than 1 value to unpack 

### ISSUE THREAD

**Issue by Infiniverse** [hannseman/hipsaint#35]
I'm getting an error message trying to use this:

    root@icinga-master:/usr/local/etc/icinga2/conf.d # hipsaint --user=Icinga --token=THETOKEN --room=THEROOM --type=service --inputs="Hello World" -n
    Traceback (most recent call last):
    File "/usr/local/bin/hipsaint", line 11, in <module>
    sys.exit(main())
    File "/usr/local/lib/python2.7/site-packages/hipsaint/bin/commands.py", line 78, in main
    msg.deliver_payload()
    File "/usr/local/lib/python2.7/site-packages/hipsaint/messages.py", line 58, in deliver_payload_v1
    message_body = self.render_message()
    File "/usr/local/lib/python2.7/site-packages/hipsaint/messages.py", line 146, in render_message
    template_context = self.get_service_context()
    File "/usr/local/lib/python2.7/site-packages/hipsaint/messages.py", line 126, in get_service_context
    servicedesc, hostalias, timestamp, ntype, hostaddress, state, serviceoutput = self.inputs_list
      ValueError: need more than 1 value to unpack

**Comment by hannseman** [comment]
Hi! Pretty bad error message and documentation about this but you need to supply a string separated by six `|` -characters. 

Try this:
```
hipsaint --user=Icinga --token=THETOKEN --room=THEROOM --type=service --inputs="HOSTNAME|LONGDATETIME|NOTIFICATIONTYPE|HOSTADDRESS|HOSTSTATE|HOSTOUTPUT" -n
```

And when using the command with icinga you'll want to wrap each value with `$`-characters to get the correct variables:

`"$HOSTNAME$|$LONGDATETIME$|$NOTIFICATIONTYPE$|$HOSTADDRESS$|$HOSTSTATE$|$HOSTOUTPUT$"`

**Comment by Infiniverse** [comment]
Not to worry - I ended up coding up my own in python in the end as it's reasonably trivial to do:

```
#!/usr/local/bin/python2

import sys
import json
import subprocess

host = "mydomain.hipchat.com"
room = 12345678
key = "API-KEY"

request = {
    "color": "green",
    "notify": "true",
    "message": sys.stdin.read(),
    "message_format": "text",
}

proc = subprocess.Popen([
    "/usr/local/bin/curl",
    "-H",
    "Content-Type: application/json",
    "https://{0}/v2/room/{1}/notification?auth_token={2}".format(host, room, key),
    "-d",
    "@-"], stdin=subprocess.PIPE)
proc.communicate(json.dumps(request))
```

with

```
#!/usr/local/bin/python2

import os
import subprocess

e = os.environ

header = e['NOTIFICATIONTYPE']
if header == "CUSTOM":
        header = "{0}: '{1}'".format(e['NOTIFICATIONAUTHORNAME'], e['NOTIFICATIONCOMMENT'])

msg = "{0} - {1} is {2} {3} - Info: {4} ({5})".format(
        header,
        e['HOSTALIAS'],
        e['HOSTSTATE'],
        e['LONGDATETIME'],
        e['HOSTOUTPUT'],
        e['HOSTADDRESS'])

dir_path = os.path.dirname(os.path.realpath(__file__))
proc = subprocess.Popen(["{0}/notify_via_hipchat.py".format(dir_path)], stdin=subprocess.PIPE)
proc.communicate(msg)
```
